{{- if .Values.dataService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dataService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.dataService.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dataService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.dataService.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.dataService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.dataService.name }}
---
{{- if .Values.dataService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.dataService.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.dataService.name }}
  minReplicas: {{ .Values.dataService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.dataService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.dataService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
