---
# Client service — internal ClusterIP for app connections
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: customer1
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
