apiVersion: v1
kind: Service
metadata:
  name: landscaping-business-svc
  namespace: landscaping-business
  annotations:
    networking.gke.io/healthcheck-policy: landscaping-business-healthcheck
spec:
  selector:
    app: landscaping-business
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
