apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.global.environment }}
    environment: {{ .Values.global.environment | quote }}
    {{- end }}
    {{- if .Values.global.clusterName }}
    cluster: {{ .Values.global.clusterName | quote }}
    {{- end }}
