apiVersion: v1
kind: Service
metadata:
  name: news-service
  namespace: customer1
  labels:
    app: news-service
    app.kubernetes.io/name: news-service
    app.kubernetes.io/component: microservice
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: news-service
