apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: SITE_NAME-healthcheck
  namespace: SITE_NAMESPACE
spec:
  targetRef:
    group: ""
    kind: Service
    name: SITE_NAME-svc
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /
