---
apiVersion: v1
kind: Service
metadata:
  name: data-service-ingester
  namespace: customer1
  labels:
    app: data-service
    component: ingester
spec:
  type: ClusterIP
  selector:
    app: data-service
    component: ingester
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: data-service-consumer
  namespace: customer1
  labels:
    app: data-service
    component: consumer
spec:
  type: ClusterIP
  selector:
    app: data-service
    component: consumer
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
