apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: execute-service-mtls-cert
  namespace: customer1
spec:
  secretName: execute-service-mtls-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: execute-service.customer1.svc.cluster.local
  dnsNames:
    - execute-service
    - execute-service.customer1
    - execute-service.customer1.svc
    - execute-service.customer1.svc.cluster.local
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
  issuerRef:
    name: trading-platform-ca-issuer
    kind: Issuer
    group: cert-manager.io
